name: Generate Space Shooter GIF

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: czl9707/gh-space-shooter@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: syedaliabbas1
          output-path: assets/space-shooter.gif
          strategy: random
          fps: 40
